//
//  DisplayViewController.swift
//  EndoProject
//
//  Created by Jess on 4/16/22.
//
import AVFoundation
import Photos
import UIKit
import Foundation
import ImageIO
import MobileCoreServices


class DisplayViewController: UIViewController {

    
    @IBOutlet weak var rewindButton: UIButton!
    @IBOutlet weak var pauseButton: UIButton!
    @IBOutlet weak var startButton: UIButton!
    @IBOutlet weak var darkModeLabel: UILabel!
    @IBOutlet weak var darkModeToggle: UISwitch!
    @IBOutlet weak var imageView: UIImageView!

    var images: [UIImage]!
    var animatedImage: UIImage!

    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .white
        
        darkModeToggleFunc()
        clickingStart()
        clickingPause()
        clickingRewind()

        // array of 300 images
        /*
         images = [UIImage(named: "ezgif-frame-1.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-2.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-3.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-4.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-5.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-6.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-7.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-8.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-9.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-10.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-11.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-12.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-13.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-14.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-15.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-16.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-17.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-18.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-19.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-20.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-21.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-22.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-23.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-24.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-25.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-26.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-27.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-28.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-29.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-30.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-31.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-32.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-33.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-34.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-35.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-36.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-37.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-38.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-39.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-40.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-41.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-42.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-43.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-44.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-45.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-46.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-47.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-48.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-49.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-50.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-51.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-52.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-53.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-54.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-55.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-56.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-57.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-58.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-59.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-60.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-61.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-62.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-63.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-64.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-65.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-66.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-67.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-68.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-69.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-70.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-71.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-72.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-73.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-74.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-75.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-76.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-77.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-78.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-79.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-80.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-81.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-82.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-83.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-84.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-85.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-86.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-87.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-88.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-89.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-90.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-91.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-92.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-93.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-94.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-95.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-96.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-97.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-98.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-99.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-100.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-101.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-102.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-103.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-104.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-105.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-106.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-107.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-108.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-109.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-110.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-111.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-112.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-113.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-114.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-115.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-116.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-117.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-118.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-119.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-120.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-121.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-122.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-123.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-124.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-125.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-126.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-127.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-128.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-129.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-130.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-131.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-132.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-133.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-134.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-135.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-136.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-137.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-138.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-139.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-140.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-141.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-142.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-143.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-144.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-145.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-146.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-147.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-148.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-149.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-150.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-151.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-152.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-153.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-154.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-155.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-156.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-157.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-158.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-159.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-160.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-161.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-162.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-163.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-164.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-165.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-166.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-167.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-168.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-169.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-170.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-171.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-172.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-173.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-174.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-175.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-176.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-177.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-178.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-179.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-180.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-181.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-182.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-183.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-184.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-185.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-186.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-187.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-188.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-189.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-190.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-191.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-192.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-193.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-194.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-195.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-196.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-197.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-198.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-199.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-200.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-201.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-202.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-203.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-204.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-205.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-206.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-207.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-208.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-209.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-210.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-211.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-212.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-213.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-214.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-215.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-216.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-217.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-218.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-219.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-220.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-221.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-222.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-223.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-224.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-225.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-226.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-227.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-228.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-229.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-230.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-231.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-232.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-233.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-234.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-235.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-236.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-237.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-238.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-239.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-240.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-241.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-242.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-243.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-244.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-245.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-246.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-247.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-248.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-249.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-250.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-251.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-252.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-253.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-254.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-255.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-256.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-257.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-258.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-259.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-260.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-261.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-262.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-263.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-264.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-265.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-266.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-267.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-268.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-269.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-270.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-271.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-272.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-273.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-274.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-275.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-276.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-277.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-278.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-279.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-280.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-281.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-282.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-283.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-284.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-285.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-286.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-287.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-288.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-289.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-290.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-291.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-292.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-293.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-294.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-295.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-296.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-297.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-298.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-299.jpg")!.resized(to: CGSize(width: 400, height: 400)),
                   UIImage(named: "ezgif-frame-300.jpg")!.resized(to: CGSize(width: 400, height: 400))]
         */
        
        images = [UIImage(named: "0001.jpg")!,
                  UIImage(named: "0002.jpg")!,
                  UIImage(named: "0003.jpg")!,
                  UIImage(named: "0004.jpg")!,
                  UIImage(named: "0005.jpg")!,
                  UIImage(named: "0006.jpg")!,
                  UIImage(named: "0007.jpg")!,
                  UIImage(named: "0008.jpg")!,
                  UIImage(named: "0009.jpg")!,
                  UIImage(named: "0010.jpg")!,
                  UIImage(named: "0011.jpg")!,
                  UIImage(named: "0012.jpg")!,
                  UIImage(named: "0013.jpg")!,
                  UIImage(named: "0014.jpg")!,
                  UIImage(named: "0015.jpg")!,
                  UIImage(named: "0016.jpg")!,
                  UIImage(named: "0017.jpg")!,
                  UIImage(named: "0018.jpg")!,
                  UIImage(named: "0019.jpg")!,
                  UIImage(named: "0020.jpg")!,
                  UIImage(named: "0021.jpg")!,
                  UIImage(named: "0022.jpg")!,
                  UIImage(named: "0023.jpg")!,
                  UIImage(named: "0024.jpg")!,
                  UIImage(named: "0025.jpg")!,
                  UIImage(named: "0026.jpg")!,
                  UIImage(named: "0027.jpg")!,
                  UIImage(named: "0028.jpg")!,
                  UIImage(named: "0029.jpg")!,
                  UIImage(named: "0030.jpg")!,
                  UIImage(named: "0031.jpg")!,
                  UIImage(named: "0032.jpg")!,
                  UIImage(named: "0033.jpg")!,
                  UIImage(named: "0034.jpg")!,
                  UIImage(named: "0035.jpg")!,
                  UIImage(named: "0036.jpg")!,
                  UIImage(named: "0037.jpg")!,
                  UIImage(named: "0038.jpg")!,
                  UIImage(named: "0039.jpg")!,
                  UIImage(named: "0040.jpg")!,
                  UIImage(named: "0041.jpg")!,
                  UIImage(named: "0042.jpg")!,
                  UIImage(named: "0043.jpg")!,
                  UIImage(named: "0044.jpg")!,
                  UIImage(named: "0045.jpg")!,
                  UIImage(named: "0046.jpg")!,
                  UIImage(named: "0047.jpg")!,
                  UIImage(named: "0048.jpg")!,
                  UIImage(named: "0049.jpg")!,
                  UIImage(named: "0050.jpg")!,
                  UIImage(named: "0051.jpg")!,
                  UIImage(named: "0052.jpg")!,
                  UIImage(named: "0053.jpg")!,
                  UIImage(named: "0054.jpg")!,
                  UIImage(named: "0055.jpg")!,
                  UIImage(named: "0056.jpg")!,
                  UIImage(named: "0057.jpg")!,
                  UIImage(named: "0058.jpg")!,
                  UIImage(named: "0059.jpg")!,
                  UIImage(named: "0060.jpg")!,
                  UIImage(named: "0061.jpg")!,
                  UIImage(named: "0062.jpg")!,
                  UIImage(named: "0063.jpg")!,
                  UIImage(named: "0064.jpg")!,
                  UIImage(named: "0065.jpg")!,
                  UIImage(named: "0066.jpg")!,
                  UIImage(named: "0067.jpg")!,
                  UIImage(named: "0068.jpg")!,
                  UIImage(named: "0069.jpg")!,
                  UIImage(named: "0070.jpg")!,
                  UIImage(named: "0071.jpg")!,
                  UIImage(named: "0072.jpg")!,
                  UIImage(named: "0073.jpg")!,
                  UIImage(named: "0074.jpg")!,
                  UIImage(named: "0075.jpg")!,
                  UIImage(named: "0076.jpg")!,
                  UIImage(named: "0077.jpg")!,
                  UIImage(named: "0078.jpg")!,
                  UIImage(named: "0079.jpg")!,
                  UIImage(named: "0080.jpg")!,
                  UIImage(named: "0081.jpg")!,
                  UIImage(named: "0082.jpg")!,
                  UIImage(named: "0083.jpg")!,
                  UIImage(named: "0084.jpg")!,
                  UIImage(named: "0085.jpg")!,
                  UIImage(named: "0086.jpg")!,
                  UIImage(named: "0087.jpg")!,
                  UIImage(named: "0088.jpg")!,
                  UIImage(named: "0089.jpg")!,
                  UIImage(named: "0090.jpg")!,
                  UIImage(named: "0091.jpg")!,
                  UIImage(named: "0092.jpg")!,
                  UIImage(named: "0093.jpg")!,
                  UIImage(named: "0094.jpg")!,
                  UIImage(named: "0095.jpg")!,
                  UIImage(named: "0096.jpg")!,
                  UIImage(named: "0097.jpg")!,
                  UIImage(named: "0098.jpg")!,
                  UIImage(named: "0099.jpg")!,
                  UIImage(named: "0100.jpg")!,
                  UIImage(named: "0101.jpg")!,
                  UIImage(named: "0102.jpg")!,
                  UIImage(named: "0103.jpg")!,
                  UIImage(named: "0104.jpg")!,
                  UIImage(named: "0105.jpg")!,
                  UIImage(named: "0106.jpg")!,
                  UIImage(named: "0107.jpg")!,
                  UIImage(named: "0108.jpg")!,
                  UIImage(named: "0109.jpg")!,
                  UIImage(named: "0110.jpg")!,
                  UIImage(named: "0111.jpg")!,
                  UIImage(named: "0112.jpg")!,
                  UIImage(named: "0113.jpg")!,
                  UIImage(named: "0114.jpg")!,
                  UIImage(named: "0115.jpg")!,
                  UIImage(named: "0116.jpg")!,
                  UIImage(named: "0117.jpg")!,
                  UIImage(named: "0118.jpg")!,
                  UIImage(named: "0119.jpg")!,
                  UIImage(named: "0120.jpg")!,
                  UIImage(named: "0121.jpg")!,
                  UIImage(named: "0122.jpg")!,
                  UIImage(named: "0123.jpg")!,
                  UIImage(named: "0124.jpg")!,
                  UIImage(named: "0125.jpg")!,
                  UIImage(named: "0126.jpg")!,
                  UIImage(named: "0127.jpg")!,
                  UIImage(named: "0128.jpg")!,
                  UIImage(named: "0129.jpg")!,
                  UIImage(named: "0130.jpg")!,
                  UIImage(named: "0131.jpg")!,
                  UIImage(named: "0132.jpg")!,
                  UIImage(named: "0133.jpg")!,
                  UIImage(named: "0134.jpg")!,
                  UIImage(named: "0135.jpg")!,
                  UIImage(named: "0136.jpg")!,
                  UIImage(named: "0137.jpg")!,
                  UIImage(named: "0138.jpg")!,
                  UIImage(named: "0139.jpg")!,
                  UIImage(named: "0140.jpg")!,
                  UIImage(named: "0141.jpg")!,
                  UIImage(named: "0142.jpg")!,
                  UIImage(named: "0143.jpg")!,
                  UIImage(named: "0144.jpg")!,
                  UIImage(named: "0145.jpg")!,
                  UIImage(named: "0146.jpg")!,
                  UIImage(named: "0147.jpg")!,
                  UIImage(named: "0148.jpg")!,
                  UIImage(named: "0149.jpg")!,
                  UIImage(named: "0150.jpg")!,
                  UIImage(named: "0151.jpg")!,
                  UIImage(named: "0152.jpg")!,
                  UIImage(named: "0153.jpg")!,
                  UIImage(named: "0154.jpg")!,
                  UIImage(named: "0155.jpg")!,
                  UIImage(named: "0156.jpg")!,
                  UIImage(named: "0157.jpg")!,
                  UIImage(named: "0158.jpg")!,
                  UIImage(named: "0159.jpg")!,
                  UIImage(named: "0160.jpg")!,
                  UIImage(named: "0161.jpg")!,
                  UIImage(named: "0162.jpg")!,
                  UIImage(named: "0163.jpg")!,
                  UIImage(named: "0164.jpg")!,
                  UIImage(named: "0165.jpg")!,
                  UIImage(named: "0166.jpg")!,
                  UIImage(named: "0167.jpg")!,
                  UIImage(named: "0168.jpg")!,
                  UIImage(named: "0169.jpg")!,
                  UIImage(named: "0170.jpg")!,
                  UIImage(named: "0171.jpg")!,
                  UIImage(named: "0172.jpg")!,
                  UIImage(named: "0173.jpg")!,
                  UIImage(named: "0174.jpg")!,
                  UIImage(named: "0175.jpg")!,
                  UIImage(named: "0176.jpg")!,
                  UIImage(named: "0177.jpg")!,
                  UIImage(named: "0178.jpg")!,
                  UIImage(named: "0179.jpg")!,
                  UIImage(named: "0180.jpg")!,
                  UIImage(named: "0181.jpg")!,
                  UIImage(named: "0182.jpg")!,
                  UIImage(named: "0183.jpg")!,
                  UIImage(named: "0184.jpg")!,
                  UIImage(named: "0185.jpg")!,
                  UIImage(named: "0186.jpg")!,
                  UIImage(named: "0187.jpg")!,
                  UIImage(named: "0188.jpg")!,
                  UIImage(named: "0189.jpg")!,
                  UIImage(named: "0190.jpg")!,
                  UIImage(named: "0191.jpg")!,
                  UIImage(named: "0192.jpg")!,
                  UIImage(named: "0193.jpg")!,
                  UIImage(named: "0194.jpg")!,
                  UIImage(named: "0195.jpg")!,
                  UIImage(named: "0196.jpg")!,
                  UIImage(named: "0197.jpg")!,
                  UIImage(named: "0198.jpg")!,
                  UIImage(named: "0199.jpg")!,
                  UIImage(named: "0200.jpg")!,
                  UIImage(named: "0201.jpg")!,
                  UIImage(named: "0202.jpg")!,
                  UIImage(named: "0203.jpg")!,
                  UIImage(named: "0204.jpg")!,
                  UIImage(named: "0205.jpg")!,
                  UIImage(named: "0206.jpg")!,
                  UIImage(named: "0207.jpg")!,
                  UIImage(named: "0208.jpg")!,
                  UIImage(named: "0209.jpg")!,
                  UIImage(named: "0210.jpg")!,
                  UIImage(named: "0211.jpg")!,
                  UIImage(named: "0212.jpg")!,
                  UIImage(named: "0213.jpg")!,
                  UIImage(named: "0214.jpg")!,
                  UIImage(named: "0215.jpg")!,
                  UIImage(named: "0216.jpg")!,
                  UIImage(named: "0217.jpg")!,
                  UIImage(named: "0218.jpg")!,
                  UIImage(named: "0219.jpg")!,
                  UIImage(named: "0220.jpg")!,
                  UIImage(named: "0221.jpg")!,
                  UIImage(named: "0222.jpg")!,
                  UIImage(named: "0223.jpg")!,
                  UIImage(named: "0224.jpg")!,
                  UIImage(named: "0225.jpg")!,
                  UIImage(named: "0226.jpg")!,
                  UIImage(named: "0227.jpg")!,
                  UIImage(named: "0228.jpg")!,
                  UIImage(named: "0229.jpg")!,
                  UIImage(named: "0230.jpg")!,
                  UIImage(named: "0231.jpg")!,
                  UIImage(named: "0232.jpg")!,
                  UIImage(named: "0233.jpg")!,
                  UIImage(named: "0234.jpg")!,
                  UIImage(named: "0235.jpg")!,
                  UIImage(named: "0236.jpg")!,
                  UIImage(named: "0237.jpg")!,
                  UIImage(named: "0238.jpg")!,
                  UIImage(named: "0239.jpg")!,
                  UIImage(named: "0240.jpg")!,
                  UIImage(named: "0241.jpg")!,
                  UIImage(named: "0242.jpg")!,
                  UIImage(named: "0243.jpg")!,
                  UIImage(named: "0244.jpg")!,
                  UIImage(named: "0245.jpg")!,
                  UIImage(named: "0246.jpg")!,
                  UIImage(named: "0247.jpg")!,
                  UIImage(named: "0248.jpg")!,
                  UIImage(named: "0249.jpg")!,
                  UIImage(named: "0250.jpg")!,
                  UIImage(named: "0251.jpg")!,
                  UIImage(named: "0252.jpg")!,
                  UIImage(named: "0253.jpg")!,
                  UIImage(named: "0254.jpg")!,
                  UIImage(named: "0255.jpg")!,
                  UIImage(named: "0256.jpg")!,
                  UIImage(named: "0257.jpg")!,
                  UIImage(named: "0258.jpg")!,
                  UIImage(named: "0259.jpg")!,
                  UIImage(named: "0260.jpg")!,
                  UIImage(named: "0261.jpg")!,
                  UIImage(named: "0262.jpg")!,
                  UIImage(named: "0263.jpg")!,
                  UIImage(named: "0264.jpg")!,
                  UIImage(named: "0265.jpg")!,
                  UIImage(named: "0266.jpg")!,
                  UIImage(named: "0267.jpg")!,
                  UIImage(named: "0268.jpg")!,
                  UIImage(named: "0269.jpg")!,
                  UIImage(named: "0270.jpg")!,
                  UIImage(named: "0271.jpg")!,
                  UIImage(named: "0272.jpg")!,
                  UIImage(named: "0273.jpg")!,
                  UIImage(named: "0274.jpg")!,
                  UIImage(named: "0275.jpg")!,
                  UIImage(named: "0276.jpg")!,
                  UIImage(named: "0277.jpg")!,
                  UIImage(named: "0278.jpg")!,
                  UIImage(named: "0279.jpg")!,
                  UIImage(named: "0280.jpg")!,
                  UIImage(named: "0281.jpg")!,
                  UIImage(named: "0282.jpg")!,
                  UIImage(named: "0283.jpg")!,
                  UIImage(named: "0284.jpg")!,
                  UIImage(named: "0285.jpg")!,
                  UIImage(named: "0286.jpg")!,
                  UIImage(named: "0287.jpg")!,
                  UIImage(named: "0288.jpg")!,
                  UIImage(named: "0289.jpg")!,
                  UIImage(named: "0290.jpg")!,
                  UIImage(named: "0291.jpg")!,
                  UIImage(named: "0292.jpg")!,
                  UIImage(named: "0293.jpg")!,
                  UIImage(named: "0294.jpg")!,
                  UIImage(named: "0295.jpg")!,
                  UIImage(named: "0296.jpg")!,
                  UIImage(named: "0297.jpg")!,
                  UIImage(named: "0298.jpg")!,
                  UIImage(named: "0299.jpg")!,
                  UIImage(named: "0300.jpg")!,
                  UIImage(named: "0301.jpg")!,
                  UIImage(named: "0302.jpg")!,
                  UIImage(named: "0303.jpg")!,
                  UIImage(named: "0304.jpg")!,
                  UIImage(named: "0305.jpg")!,
                  UIImage(named: "0306.jpg")!,
                  UIImage(named: "0307.jpg")!,
                  UIImage(named: "0308.jpg")!,
                  UIImage(named: "0309.jpg")!,
                  UIImage(named: "0310.jpg")!,
                  UIImage(named: "0311.jpg")!,
                  UIImage(named: "0312.jpg")!,
                  UIImage(named: "0313.jpg")!,
                  UIImage(named: "0314.jpg")!,
                  UIImage(named: "0315.jpg")!,
                  UIImage(named: "0316.jpg")!,
                  UIImage(named: "0317.jpg")!,
                  UIImage(named: "0318.jpg")!,
                  UIImage(named: "0319.jpg")!,
                  UIImage(named: "0320.jpg")!,
                  UIImage(named: "0321.jpg")!,
                  UIImage(named: "0322.jpg")!,
                  UIImage(named: "0323.jpg")!,
                  UIImage(named: "0324.jpg")!,
                  UIImage(named: "0325.jpg")!,
                  UIImage(named: "0326.jpg")!,
                  UIImage(named: "0327.jpg")!,
                  UIImage(named: "0328.jpg")!,
                  UIImage(named: "0329.jpg")!,
                  UIImage(named: "0330.jpg")!,
                  UIImage(named: "0331.jpg")!,
                  UIImage(named: "0332.jpg")!,
                  UIImage(named: "0333.jpg")!,
                  UIImage(named: "0334.jpg")!,
                  UIImage(named: "0335.jpg")!,
                  UIImage(named: "0336.jpg")!,
                  UIImage(named: "0337.jpg")!,
                  UIImage(named: "0338.jpg")!,
                  UIImage(named: "0339.jpg")!,
                  UIImage(named: "0340.jpg")!,
                  UIImage(named: "0341.jpg")!,
                  UIImage(named: "0342.jpg")!,
                  UIImage(named: "0343.jpg")!,
                  UIImage(named: "0344.jpg")!,
                  UIImage(named: "0345.jpg")!,
                  UIImage(named: "0346.jpg")!,
                  UIImage(named: "0347.jpg")!,
                  UIImage(named: "0348.jpg")!,
                  UIImage(named: "0349.jpg")!,
                  UIImage(named: "0350.jpg")!,
                  UIImage(named: "0351.jpg")!,
                  UIImage(named: "0352.jpg")!,
                  UIImage(named: "0353.jpg")!,
                  UIImage(named: "0354.jpg")!,
                  UIImage(named: "0355.jpg")!,
                  UIImage(named: "0356.jpg")!,
                  UIImage(named: "0357.jpg")!,
                  UIImage(named: "0358.jpg")!,
                  UIImage(named: "0359.jpg")!,
                  UIImage(named: "0360.jpg")!,
                  UIImage(named: "0361.jpg")!,
                  UIImage(named: "0362.jpg")!,
                  UIImage(named: "0363.jpg")!,
                  UIImage(named: "0364.jpg")!,
                  UIImage(named: "0365.jpg")!,
                  UIImage(named: "0366.jpg")!,
                  UIImage(named: "0367.jpg")!,
                  UIImage(named: "0368.jpg")!,
                  UIImage(named: "0369.jpg")!,
                  UIImage(named: "0370.jpg")!,
                  UIImage(named: "0371.jpg")!,
                  UIImage(named: "0372.jpg")!,
                  UIImage(named: "0373.jpg")!,
                  UIImage(named: "0374.jpg")!,
                  UIImage(named: "0375.jpg")!,
                  UIImage(named: "0376.jpg")!,
                  UIImage(named: "0377.jpg")!,
                  UIImage(named: "0378.jpg")!,
                  UIImage(named: "0379.jpg")!,
                  UIImage(named: "0380.jpg")!,
                  UIImage(named: "0381.jpg")!,
                  UIImage(named: "0382.jpg")!,
                  UIImage(named: "0383.jpg")!,
                  UIImage(named: "0384.jpg")!,
                  UIImage(named: "0385.jpg")!,
                  UIImage(named: "0386.jpg")!,
                  UIImage(named: "0387.jpg")!,
                  UIImage(named: "0388.jpg")!,
                  UIImage(named: "0389.jpg")!,
                  UIImage(named: "0390.jpg")!,
                  UIImage(named: "0391.jpg")!,
                  UIImage(named: "0392.jpg")!,
                  UIImage(named: "0393.jpg")!,
                  UIImage(named: "0394.jpg")!,
                  UIImage(named: "0395.jpg")!,
                  UIImage(named: "0396.jpg")!,
                  UIImage(named: "0397.jpg")!,
                  UIImage(named: "0398.jpg")!,
                  UIImage(named: "0399.jpg")!,
                  UIImage(named: "0400.jpg")!,
                  UIImage(named: "0401.jpg")!,
                  UIImage(named: "0402.jpg")!,
                  UIImage(named: "0403.jpg")!,
                  UIImage(named: "0404.jpg")!,
                  UIImage(named: "0405.jpg")!,
                  UIImage(named: "0406.jpg")!,
                  UIImage(named: "0407.jpg")!,
                  UIImage(named: "0408.jpg")!,
                  UIImage(named: "0409.jpg")!,
                  UIImage(named: "0410.jpg")!,
                  UIImage(named: "0411.jpg")!,
                  UIImage(named: "0412.jpg")!,
                  UIImage(named: "0413.jpg")!,
                  UIImage(named: "0414.jpg")!,
                  UIImage(named: "0415.jpg")!,
                  UIImage(named: "0416.jpg")!,
                  UIImage(named: "0417.jpg")!,
                  UIImage(named: "0418.jpg")!,
                  UIImage(named: "0419.jpg")!,
                  UIImage(named: "0420.jpg")!,
                  UIImage(named: "0421.jpg")!,
                  UIImage(named: "0422.jpg")!,
                  UIImage(named: "0423.jpg")!,
                  UIImage(named: "0424.jpg")!,
                  UIImage(named: "0425.jpg")!,
                  UIImage(named: "0426.jpg")!,
                  UIImage(named: "0427.jpg")!,
                  UIImage(named: "0428.jpg")!,
                  UIImage(named: "0429.jpg")!,
                  UIImage(named: "0430.jpg")!,
                  UIImage(named: "0431.jpg")!,
                  UIImage(named: "0432.jpg")!,
                  UIImage(named: "0433.jpg")!,
                  UIImage(named: "0434.jpg")!,
                  UIImage(named: "0435.jpg")!,
                  UIImage(named: "0436.jpg")!,
                  UIImage(named: "0437.jpg")!,
                  UIImage(named: "0438.jpg")!,
                  UIImage(named: "0439.jpg")!,
                  UIImage(named: "0440.jpg")!,
                  UIImage(named: "0441.jpg")!,
                  UIImage(named: "0442.jpg")!,
                  UIImage(named: "0443.jpg")!,
                  UIImage(named: "0444.jpg")!,
                  UIImage(named: "0445.jpg")!,
                  UIImage(named: "0446.jpg")!,
                  UIImage(named: "0447.jpg")!,
                  UIImage(named: "0448.jpg")!,
                  UIImage(named: "0449.jpg")!,
                  UIImage(named: "0450.jpg")!,
                  UIImage(named: "0451.jpg")!,
                  UIImage(named: "0452.jpg")!,
                  UIImage(named: "0453.jpg")!,
                  UIImage(named: "0454.jpg")!,
                  UIImage(named: "0455.jpg")!,
                  UIImage(named: "0456.jpg")!,
                  UIImage(named: "0457.jpg")!,
                  UIImage(named: "0458.jpg")!,
                  UIImage(named: "0459.jpg")!,
                  UIImage(named: "0460.jpg")!,
                  UIImage(named: "0461.jpg")!,
                  UIImage(named: "0462.jpg")!,
                  UIImage(named: "0463.jpg")!,
                  UIImage(named: "0464.jpg")!,
                  UIImage(named: "0465.jpg")!,
                  UIImage(named: "0466.jpg")!,
                  UIImage(named: "0467.jpg")!,
                  UIImage(named: "0468.jpg")!,
                  UIImage(named: "0469.jpg")!,
                  UIImage(named: "0470.jpg")!,
                  UIImage(named: "0471.jpg")!,
                  UIImage(named: "0472.jpg")!,
                  UIImage(named: "0473.jpg")!,
                  UIImage(named: "0474.jpg")!,
                  UIImage(named: "0475.jpg")!,
                  UIImage(named: "0476.jpg")!,
                  UIImage(named: "0477.jpg")!,
                  UIImage(named: "0478.jpg")!,
                  UIImage(named: "0479.jpg")!,
                  UIImage(named: "0480.jpg")!,
                  UIImage(named: "0481.jpg")!,
                  UIImage(named: "0482.jpg")!,
                  UIImage(named: "0483.jpg")!,
                  UIImage(named: "0484.jpg")!,
                  UIImage(named: "0485.jpg")!,
                  UIImage(named: "0486.jpg")!,
                  UIImage(named: "0487.jpg")!,
                  UIImage(named: "0488.jpg")!,
                  UIImage(named: "0489.jpg")!,
                  UIImage(named: "0490.jpg")!,
                  UIImage(named: "0491.jpg")!,
                  UIImage(named: "0492.jpg")!,
                  UIImage(named: "0493.jpg")!,
                  UIImage(named: "0494.jpg")!,
                  UIImage(named: "0495.jpg")!, UIImage(named: "0496.jpg")!, UIImage(named: "0497.jpg")!, UIImage(named: "0498.jpg")!, UIImage(named: "0499.jpg")!, UIImage(named: "0500.jpg")!]
        
        
        //imageView.animationImages = images
        // alterImage()
        //let  imageView =  UIImageView()
        imageView.animationImages = images //images is your array
        
         
    }
    
    func darkModeToggleFunc()
    {
        view.addSubview(darkModeToggle)
        darkModeToggle.addTarget(self, action: #selector(darkModeAction), for: .touchUpInside)
        
    }
    
    @objc func darkModeAction(  toggle: UISwitch)
    {
        if toggle.isOn
        {
            view.backgroundColor = .black
            darkModeLabel.textColor = .white
        }
        
        else
        {
      
            view.backgroundColor = .white
            darkModeLabel.textColor = .black
            
        }
        
    }
    
    
    func clickingStart()
    {
        startButton.addTarget(self, action: #selector(buttonClicked), for: .touchUpInside)
    }
    @objc func buttonClicked(_ sender: Any) {
        
        imageView.startAnimating()

        self.resumeLayer(layer: imageView.layer)
    }
    func resumeLayer(layer: CALayer) {
        let pausedTime = layer.timeOffset
        layer.speed = 1.0
        layer.timeOffset = 0.0
        layer.beginTime = 0.0
        let timeSincePause = layer.convertTime(CACurrentMediaTime(), from: nil) - pausedTime
        layer.beginTime = timeSincePause
    }
    
    
    
    
    func clickingPause()
    {
        pauseButton.addTarget(self, action: #selector(buttonClickedPause), for: .touchUpInside)
    }
    @objc func buttonClickedPause(_ sender: Any) {
        self.pauseLayer(layer: imageView.layer)
    }
    
    
    func pauseLayer(layer: CALayer) {
        let pausedTime = layer.convertTime(CACurrentMediaTime(), from: nil)
        layer.speed = 0.0
        layer.timeOffset = pausedTime
    }
    
    
    func clickingRewind()
    {
        rewindButton.addTarget(self, action: #selector(buttonClickedRewind), for: .touchUpInside)
    }
    
    @objc func buttonClickedRewind(_ sender: Any) {
        self.rewindLayer(layer: imageView.layer)
    }
    
    
    func rewindLayer(layer: CALayer) {
        let pausedTime = layer.convertTime(CACurrentMediaTime(), from: nil) - 1
        layer.speed = 0.0
        layer.timeOffset = pausedTime
    }
    
}


extension UIImage {
    func resized(to size: CGSize) -> UIImage {
        return UIGraphicsImageRenderer(size: size).image { _ in
            draw(in: CGRect(origin: .zero, size: size))
        }
    }
}

